- name: Provision VMs
  hosts: all
  vars:
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  #remote_user: onlanta
  become: yes  # If you need elevated privileges

  tasks:
    - name: Read device information (always use unit when probing)
      community.general.parted: device=/dev/sda unit=MiB
      register: sda_info

    - name: Extend an existing partition to fill all available space
      community.general.parted:
        device: /dev/sda
        number: "{{ sda_info.partitions | length }}"
        part_end: "100%"
        resize: true
        state: present

    - name: Create a volume group on top of /dev/sda3 and resize the volume group /dev/sda3 to the maximum possible
      community.general.lvg:
        vg: centos
        pvs: /dev/sda2
        pvresize: true

    - name: Extend the logical volume to consume all remaining space in the volume group
      community.general.lvol:
        vg: centos
        lv: root
        size: +100%FREE
        resizefs: true

    - name: Create the group
      group:
        name: deploy
      become: yes

    - name: Add the user 'deploy' with a bash shell, appending the group 'wheel' and 'deploy' to the user's groups
      ansible.builtin.user:
        name: centos
        shell: /bin/bash
        groups: wheel,deploy
        append: yes
        password: "{{ 'Asd#21' | password_hash('sha512', 'mysecretsalt') }}"

    - name: Copy SSH public key to authorized_keys
      ansible.builtin.authorized_key:
        user: centos
        key: "{{ lookup('file', '/home/centos/.ssh/id_rsa.pub') }}"
        state: present

    - name: copy hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: "{{ lookup('file', 'hosts.cfg')}}"

    - name: make sure chronyd is installed
      yum:
       name: chrony
       state: latest
       update_cache: yes
  
    - name: deploy chrony.conf template
      template:
       src: chrony.conf.j2
       dest: /etc/chrony.conf
       owner: root
       group: root
       mode: 0644
       backup: yes
  
    - name: Restart chronyd
      service:
        name: chronyd
        state: restarted    
